language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn
script:
  - yarn test
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build
    github_token: $GITHUB_TOKEN
    on:
      branch: master